
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: r7-dev

resources:
  - ../../base

images:
  - name: docker.io/retailfactory/backend-r7
    newTag: 9ce6d005

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SSO_MOCK_MODE
          value: "true"
