apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: r7-root
  namespace: argocd
spec:
  project: r7-project
  source:
    repoURL: git@github.com:RetailFactory/Configuracion-R7.git
    targetRevision: main
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
