apiVersion: v1
kind: ConfigMap
metadata:
  name: sap-service-layer-ca
data:
  sap-service-layer-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEcDCCAtigAwIBAgIJAOaoNcPf45VLMA0GCSqGSIb3DQEBCwUAMEMxCzAJBgNV
    BAYTAkNOMQwwCgYDVQQKEwNTQVAxCzAJBgNVBAsTAkIxMRkwFwYDVQQDExBpcC0x
    OTItMTY4LTEwMS02MB4XDTI1MDcyODIwMzU1OVoXDTI3MTAzMDIwMzU1OVowQzEL
    MAkGA1UEBhMCQ04xDDAKBgNVBAoTA1NBUDELMAkGA1UECxMCQjExGTAXBgNVBAMT
    EGlwLTE5Mi0xNjgtMTAxLTYwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIB
    gQC2+a3kjHOphXMPwzw/RiDuvXa7lE5wYZKn+wS1YLPoEk1X33SyefpXHls/OJwg
    0b2xXh2IKJy3acEw8Aoxcg1xz4sBdfIZdLY4VRBmzh1bQBSCPhpfXh6u2cvuUGka
    bjeSJF7j1dhnb3Ac2/QMNN8ogv4IcBW1dWgkmJWq91jZ4elQk4jrv7o3YZY+OKWI
    oqwHYP906jlcO62AKTpsJohLeVAGs+4ZHdBFs11KkM347vW0/7IOAVcRJZj2WjC0
    EoGFpMjJp4i6Fulm0vERehWaTqWrmiy4I34BcwutLK9psF5GHu4uc3uc9wQ6aKZJ
    3TRmG/CvnC/boxd2UGoL9dEiwwGHEn78kvFNwh7F4QPlh4D4UF0tPRUWES3AUN6s
    YNnA8zQ64PA/zE+RE1OFqxv4HBkRk2nliMuJ+dMc/VTc5KmwiFCDEWKom5TrNe7a
    kPLwxxbMpoBQ5Kzz5hf1FGdrQvqf4iEW1T3Zzg5JE7oh5cxfKknsgSJRqIHw5tpI
    bysCAwEAAaNnMGUwHQYDVR0OBBYEFEOl1xt+HezGW5mPJebAs+VfxZCuMCEGA1Ud
    EQQaMBiCEGlwLTE5Mi0xNjgtMTAxLTaHBMCoZQYwDAYDVR0TBAUwAwEB/zATBgNV
    HSUEDDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQsFAAOCAYEARIcbditHuHlKigWC
    uo7wDBJYYwLxFJz9rOmU5FBHKHV4iXyADJ4lLWLQ4brcjYkTuqIRSuQEaReqT7YU
    R9gj/0pOz+WV4ZvSmqpYyFQ3f7D7jMOMTFcJvJKlP52mqbD9CYGwXzd24LhT76D0
    I3t8iLY86UmZIqKxi0aYTDb1TtcspoSqCufoh6rgJ3JdP0irJ1FfcIDn66s8aSbq
    AF/ys4pRpC6fG69cAydudzEo7bvQdT0q6fVukmX0S2g7bsqXTeaiYirettSYTgmw
    +xEplkEkWe8Kt0CB3ALPKuS/C0/KQ1M+EmGLrGwgvogbeXWbQoOOunrbViWAU56z
    k5jYBqyf12JQyRicEkgAYn/hcNF7LgiUsCVpuDrH62+yPSK8WkqITA4PbhFdd76J
    sLS62CjE/GQXvNQCM2jZPPEdkFb+hJ4PAd3cPpn6EwJSPEBvE7UGT7VmdNc3d8x5
    LNF1YBpL+CMdcGZ9D6fjr7Q8xkeFOzE05swGgNNddXMK5NcY
    -----END CERTIFICATE-----
