apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routing-qa
  namespace: argocd
spec:
  project: r7-project
  source:
    repoURL: https://github.com/RetailFactory/Configuracion-R7.git
    targetRevision: deploy/qa
    path: apps/routing/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: r7-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
